mp=int(input("enter the marks of mp "))
ds=int(input("enter the marks of ds"))
cn=int(input("enter the marks of cn"))
sp=int(input("enter the marks of sp"))
ed=int(input("enter the marks of ed"))
os=int(input("enter the marks of os"))
percent=(mp+ds+cn+sp+ed+os)
percentage=(percent/300*100)
print("the percentage of five subject",percentage)
